### ISSUE TITLE
报错如下

### ISSUE THREAD

**Issue by zxz0119** [lw1243925457/xiuXianInvest#1]
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\zxz\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\zxz\Desktop\xiuXianInvest-master\main.py", line 62, in run
    start_game()
  File "C:\Users\zxz\Desktop\xiuXianInvest-master\main.py", line 37, in start_game
    images.load()
  File "C:\Users\zxz\Desktop\xiuXianInvest-master\common\image_source.py", line 18, in load
    metal = pygame.image.load(r"C:\Users\zxz\Desktop\Saved Pictures\metal.png").convert_alpha()
FileNotFoundError: No such file or directory: 'C:\Users\zxz\Desktop\Saved Pictures\metal.png'.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\zxz\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\zxz\Desktop\xiuXianInvest-master\main.py", line 64, in run
    start_listen()
  File "C:\Users\zxz\Desktop\xiuXianInvest-master\main.py", line 45, in start_listen
    connection = pika.BlockingConnection(pika.ConnectionParameters(
  File "C:\Users\zxz\AppData\Local\Programs\Python\Python310\lib\site-packages\pika\adapters\blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "C:\Users\zxz\AppData\Local\Programs\Python\Python310\lib\site-packages\pika\adapters\blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError`
报错如上
我已经配置好了然后发现少了图片文件也去找了 结果启动后报错了

**Comment by Vainycos** [comment]
是不是就是缺少图片的错误，我这里也报了差不多的错

**Comment by freedom-xiao007** [comment]
电脑清理过，图片资源找不到了，只能凑合用张图片让程序能跑起来了。但图片也是几张而已，就是背景图，透明图和金木水火土的图片，自己找相应的替换上也成（最近事太多了，没时间搞了，抱歉）

相关的也更新在工程里面了

**Comment by Vainycos** [comment]
收到，感谢百忙之中的答复！再次感谢



***@***.***
 
发件人： 萧
发送时间： 2022-09-28 19:38
收件人： lw1243925457/xiuXianInvest
抄送： Vainycos; Comment
主题： Re: [lw1243925457/xiuXianInvest] 报错如下 (Issue #1)
电脑清理过，图片资源找不到了，只能凑合用张图片让程序能跑起来了。但图片也是几张而已，就是背景图，透明图和金木水火土的图片，自己找相应的替换上也成（最近事太多了，没时间搞了，抱歉）
相关的也更新在工程里面了
